baseURL = "http://tixie.name"
languageCode = "en"
title = "Tixie Salander's homepage 🏠"
disableKinds = [ "taxonomy", "sitemap" ]
summaryLength = 40
paginate = 10

[markup.goldmark.renderer]
unsafe = true

[security]
    [security.funcs]
    getenv = [ "^HUGO_", "CONTEXT", "URL" ]

# ----------------
# Navigation links
# ----------------

[[menu.nav]]
identifier = "about"
name = "Me"
title = "Personal infos"
url = "/#about"
weight = 1

[[menu.nav]]
identifier = "projects"
name = "Projects"
title = "My projects"
url = "/#projects"
weight = 2

[[menu.nav]]
identifier = "links"
name = "Links"
title = "Social links"
url = "/#links"
weight = 3

[[menu.nav]]
identifier = "logs"
name = "Logs"
title = "Micro-blog"
url = "/logs/"
weight = 4

[[menu.nav]]
identifier = "contact"
name = "Contact"
title = "Contact infos"
url = "/#contact"
weight = 5
