error_page = "404.html"

[[redirects]]
from = "/now/03-17-2020-7-41-pm/"
to = "https://guerilla.studio/blog/make-colored-placeholder-hugo/"
status = 301
force = true

[[redirects]]
from = "/logs/03-17-2020-7-41-pm-make-colored-placeholder-hugo/"
to = "https://guerilla.studio/blog/make-colored-placeholder-hugo/"
status = 301
force = true

[[redirects]]
from = "/now/"
to = "/logs/"
status = 301
force = true

[[redirects]]
from = "/now/*"
to = "/logs/*"
status = 301
force = true
