[build]
  publish = "public"
  command = "hugo -b $URL"
  HUGO_VERSION = "0.62.2"

[context.production.environment]
  HUGO_ENV = "production"
  command = "hugo -b $URL"
  HUGO_VERSION = "0.62.2"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"
  HUGO_VERSION = "0.62.2"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
