[build]
  publish = "public"
  command = "hugo -b $URL"
[build.environment]
  HUGO_VERSION = "0.139.0"

[context.production.environment]
  HUGO_ENV = "production"
  command = "hugo -b $URL"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/now/03-17-2020-7-41-pm/"
  to = "https://guerilla.studio/blog/make-colored-placeholder-hugo/"
  status = 301
  force = true

[[redirects]]
  from = "/logs/03-17-2020-7-41-pm-make-colored-placeholder-hugo/"
  to = "https://guerilla.studio/blog/make-colored-placeholder-hugo/"
  status = 301
  force = true

[[redirects]]
  from = "/now/"
  to = "/logs/"
  status = 301
  force = true

[[redirects]]
  from = "/now/*"
  to = "/logs/:splat"
  status = 301
  force = true
