[build]
  publish = "public"
  command = "hugo --gc -b $URL"
[build.environment]
  HUGO_VERSION = "0.139.4"
  DART_SASS_VERSION = "1.83.0"

[context.production.environment]
  HUGO_ENV = "production"
  command = """\
    curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    export PATH=/opt/build/repo/dart-sass:$PATH && \
    hugo --gc -b $URL \
    """

[context.deploy-preview]
  command = """\
    curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    export PATH=/opt/build/repo/dart-sass:$PATH && \
    hugo --gc -b $DEPLOY_PRIME_URL \
    """

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/now/03-17-2020-7-41-pm/"
  to = "https://guerilla.studio/blog/make-colored-placeholder-hugo/"
  status = 301
  force = true

[[redirects]]
  from = "/logs/03-17-2020-7-41-pm-make-colored-placeholder-hugo/"
  to = "https://guerilla.studio/blog/make-colored-placeholder-hugo/"
  status = 301
  force = true

[[redirects]]
  from = "/now/"
  to = "/logs/"
  status = 301
  force = true

[[redirects]]
  from = "/now/*"
  to = "/logs/:splat"
  status = 301
  force = true
