---
# local_backend: true
backend:
  name: github
  repo: TixieBorg/tixie.name
  branch: main
site_url: https://tixie.name
display_url: https://tixie.name/now
media_folder: assets/upload
public_folder: /upload
collections:
  - name: now
    editor:
      preview: false
    create: true
    label: Now Status
    format: frontmatter
    folder: content/now
    sortable_fields: ['date']
    preview_path: now/{{slug}}
    media_folder: ''
    public_folder: ''
    fields:
    - name: title
      label: Title
      widget: string
    - name: date
      label: Date
      widget: datetime
    - name: body
      label: Content
      widget: markdown
      buttons: ["italic", "code", "link", "quote", "code-block", "bulleted-list", "numbered-list"]
    - name: images
      label: Gallery
      widget: list
      allow_add: true
      field: { label: Image, name: image, widget: image, required: false }
