---
local_backend: true
backend:
  name: github
  repo: TixieSalander/tixie.name
  branch: main
site_url: https://tixie.name
display_url: https://tixie.name/logs
media_folder: assets/upload
public_folder: /upload
collections:
  - name: Logs
    editor:
      preview: false
    create: true
    label: Log Status
    format: frontmatter
    folder: content/logs
    path: '{{slug}}/index'
    sortable_fields: ['date']
    preview_path: logs/{{slug}}
    media_folder: ''
    public_folder: ''
    fields:
    - name: title
      label: Title
      widget: string
    - name: show_title
      label: Show Title
      widget: boolean
      default: false
    - name: date
      label: Date
      widget: datetime
    - name: body
      label: Content
      widget: markdown
      buttons: ["bold", "italic", "code", "link", "quote", "code", "bulleted-list", "numbered-list"]
    - name: images
      required: false
      label: Gallery
      widget: list
      allow_add: true
      field: { label: Image, name: image, widget: image, required: false }
